name: Deploy to firebase

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - run: cd client && npm ci && npm run build
      - run: cd client/build && echo "/* /index.html 200" > _redirects
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: ../../client/build
          NETLIFY_DEPLOY_TO_PROD: true
